{% set name = "google-cloud-language" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 63ca2d772e16e4440858848e8c3298859b931b1652f663683fb5d7413b7c9a1b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip >=18.1
  run:
    - python >=3.6
    - google-api-core-grpc >=1.26.0,<2.0.0dev
    - proto-plus >=1.10.0
    - packaging >=14.3

test:
  imports:
    - google.cloud.language
    - google.cloud.language_v1
    - google.cloud.language__v1beta2
    - grpc

about:
  home: https://github.com/googleapis/python-language
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python Client for Google Cloud Natural Language
  description: |
    Python Client for Google Cloud Natural Language
    -------------------------

    The [Google Cloud Natural Language](https://cloud.google.com/natural-language/) API can be used to reveal the
    structure and meaning of text via powerful machine
    learning models. You can use it to extract information about
    people, places, events and much more, mentioned in text documents,
    news articles or blog posts. You can use it to understand
    sentiment about your product on social media or parse intent from
    customer conversations happening in a call center or a messaging
    app. You can analyze text uploaded in your request or integrate
    with your document storage on Google Cloud Storage.

    - [Client Library Documentation](https://googleapis.dev/python/language/latest/index.html)
    - [Product Documentation](https://cloud.google.com/language/docs)

    **note**

        This library currently does not run on Google App Engine Standard.
        We are actively working on adding this support.

    Quick Start
    -----------

    In order to use this library, you first need to go through the following steps:

    1. [Select or create a Cloud Platform project.](https://console.cloud.google.com/project)
    2. [Enable billing for your project.](https://cloud.google.com/billing/docs/how-to/modify-project#enable_billing_for_a_project)
    3. [Enable the Google Cloud Language API.](https://cloud.google.com/natural-language)
    4. [Setup Authentication.](https://googleapis.github.io/google-cloud-python/latest/core/auth.html)

    Supported Python Versions
    -----------
    Python >= 3.6


  doc_url: https://googleapis.dev/python/language/latest/index.html
  dev_url: https://github.com/googleapis/python-language

extra:
  recipe-maintainers:
    - BrentDorsey
    - parthea
