{% set name = "google-cloud-language" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/google-cloud-language-{{ version }}.tar.gz
  sha256: b47e6c4a1fde4b977c0bf69749e0aec04c4dc57c0043538914dedc736e81b7c1

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.4
    - pip
  run:
    - python >=3.4
    - google-api-core-grpc >=1.31.5,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0
    - python

test:
  imports:
    - google.cloud.language
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/google-cloud-python
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: 'Python Client for Google Cloud Natural Language'
  description: |
    Python Client for Google Cloud Natural Language
    -------------------------

    The [Google Cloud Natural Language](https://cloud.google.com/natural-language/) API can be used to reveal the
    structure and meaning of text via powerful machine
    learning models. You can use it to extract information about
    people, places, events and much more, mentioned in text documents,
    news articles or blog posts. You can use it to understand
    sentiment about your product on social media or parse intent from
    customer conversations happening in a call center or a messaging
    app. You can analyze text uploaded in your request or integrate
    with your document storage on Google Cloud Storage.

    - [Client Library Documentation](https://googleapis.github.io/google-cloud-python/latest/language/index.html)
    - [Product Documentation](https://cloud.google.com/language/docs)

    **note**

        This library currently does not run on Google App Engine Standard.
        We are actively working on adding this support.

    Quick Start
    -----------

    In order to use this library, you first need to go through the following steps:

    1. [Select or create a Cloud Platform project.](https://console.cloud.google.com/project)
    2. [Enable billing for your project.](https://cloud.google.com/billing/docs/how-to/modify-project#enable_billing_for_a_project)
    3. [Enable the Google Cloud Language API.](https://cloud.google.com/natural-language)
    4. [Setup Authentication.](https://googleapis.github.io/google-cloud-python/latest/core/auth.html)

    Supported Python Versions
    -----------
    Python >= 3.5

    Deprecated Python Versions
    -----------
    Python == 2.7. Python 2.7 support will be removed on January 1, 2020.

  doc_url: https://googleapis.github.io/google-cloud-python/latest/language/index.html
  dev_url: https://github.com/googleapis/google-cloud-python/tree/master/language

extra:
  recipe-maintainers:
    - BrentDorsey
    - parthea
    - xylar
