travis:
  secure:
    BINSTAR_TOKEN: oEiSgNSGvXy+wMMY2N+eOFk0OAJgPjqqtOGmL6jMO+lm+a+lBhDtXe+ZVNxT/BpKlWpHf/Ohsmkm5NszpYBAryFrJDoFVt5wxAg0gsgDh5BG/QT55E3D95MEOwGjn9HsFAZKRUIrTN/7KYj5RU1/NPn+sGek52Fyt2HPh2rQ8kgds7mty6Lw+AMnoS10hmU78SeEQ5CwUDYOcRuWk319w1Oh9qv5eBE5gfphNrpr8VqXBUdOE6GmXarhMM+Xt2I+yfTrPjsQqfdcadRx7VDnr9/O1qZ1vEIWoCDt3YAn0AGVSAkR1OXIVnbO3LIHFihW3m2cr4bvxd4/BE2JulL9L8Biju1MJL2jHAwaAS4AM2XNr8UlHL7goiIGQq2jDhzR2XKIL9VYY9FeSgJxRMTtyEhSEtkoWnGPQngpM8Pv4aOw5cx0y0MGO1SAuHeaWUd4Coi15BlWbiUQcglj0a5AYtx/EXKSxrbH9Hbr3TGOnxp3S6VXuQGwSJ4fUwBuW4rGMVuKdDz6HpdbAJYjXG9ewREdocXTYD8oSSzQmUh3Zfal5W+5NYfgn2icgMTPn1GNcsndXiL5qqJnvOhg77K/2Ca0FhBAGd2l8O6g/mPyLCtbeNgooR5uD+kw3QUYYlmr2VrJgMb2Em/uekkH2KMX33qql946WwlGqqZxDHjTYTg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
